<?php
    $this->form->prepare();
    $this->form->setAttribute( 'action', $this->url('register', ['action'=> 'create'] ));
    $this->form->setAttribute( 'method', 'post' );
    $this->form->setAttribute( 'class', 'form-horizontal' );
    $this->form->setAttribute( 'role', 'form' );


?>

<div class="row">
    <div class="col-sm-10">
        <div class="panel panel-primary">
            <div class="panel-heading text-center mt-5 mb-5">
                <h3 class="panel-title"><?= $this->title ?></h3>
            </div>
            <?= $this->form()->openTag($this->form);?>
            <div class="panel-body">
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('name')) ?>
                    <?= $this->formInput($this->form->get('name')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('lastname')) ?>
                    <?= $this->formInput($this->form->get('lastname')) ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($this->form->get('country')) ?>
                    <?= $this->formInput($this->form->get('country')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('city')) ?>
                    <?= $this->formInput($this->form->get('city')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('email')) ?>
                    <?= $this->formInput($this->form->get('email')) ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($this->form->get('password')) ?>
                    <?= $this->formInput($this->form->get('password')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('interest')) ?>
                    <?= $this->formInput($this->form->get('interest')) ?>
                </div>
                <div class="form-group">
                    <div class="col-sm-7 offset-sm-2">
                        <?= $this->formSubmit($this->form->get('create'))?>
                    </div>
                </div>

                <?= $this->formHidden($this->form->get('id'))?>
                <?php $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>

</div>
